version: '2'
services:
  db:
    image: postgres
    ports:
      - "3306:3306"
    volumes:
      - postgres:/var/lib/pgsql
    extends:
      file: ./docker/postgres/password.yml
      service: password
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle_install:/usr/local/bundle
    environment:
      RAILS_ENV: development
    extends:
      file: ./docker/postgres/password.yml
      service: password
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres:
    driver: local
  bundle_install:
    driver: local